#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:eapp
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=123
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true
#spring.jpa.format-sql=true

jwt:
  secret: "Interstellar-Oracle-f@tec-@p1-2@21-4semestre"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:eapp
    driverClassName: org.h2.Driver
    username: sa
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true*/

