#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:eapp
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=123
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true
#spring.jpa.format-sql=true

jwt:
  secret: "Interstellar-Oracle-f@tec-@p1-2@21-4semestre"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:oracle:thin:@DB202109231147_high?TNS_ADMIN=./key
    driverClassName: oracle.jdbc.OracleDriver
    username: ADMIN
    password: 8aYBPHjr7oudm8

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
            auto: create-drop
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true



